version: '3.8'
services:
  database:
    image: nggocnn/database:v1
    build:
      context: ./database
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - 3306:$MYSQL_PORT
    restart: always
    networks:
      - back-tier

  backend:
    image: nggocnn/backend:v1
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - 5000:$BACKEND_PORT
    depends_on:
      - database
    restart: on-failure
    networks:
      - back-tier
      - front-tier

  frontend:
    image: nggocnn/frontend:v1
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - 80:$FRONTEND_PORT
    restart: on-failure
    depends_on:
      - database
      - backend
    networks:
      - front-tier

networks:
  front-tier:
  back-tier:
