version: '3.8'
services:
  db:
    image: nggocnn/database:v1
    build: ./db
    env_file:
      - ./.env
    ports:
      - $DB_PORT
    restart: always

  backend:
    image: nggocnn/backend:v1
    build: ./backend
    env_file:
      - ./.env
    ports:
      - 5000:$BACKEND_PORT
    depends_on:
      - db
    restart: on-failure

  frontend:
    image: nggocnn/frontend:v1
    build:
      context: ./frontend
      args:
        BACKEND_SERVICE: $BACKEND_SERVICE
        BACKEND_PORT: $BACKEND_PORT
    env_file:
      - ./.env
    ports:
      - $HOST_PORT:$FRONTEND_PORT
    restart: on-failure
    depends_on:
      - db
      - backend
